static const char *const if_types[] = {
"Name",
"other",
"regular1822",
"hdh1822",
"ddn-x25",
"x25",
"ethernet-csmacd",
"IEEE802.3",
"IEEE802.4",
"IEEE802.5",
"iso88026-man",
"starLan",
"proteon-10Mbit",
"proteon-80Mbit",
"hyperchannel",
"FDDI",
"lapb",
"sdlc",
"ds1",
"e1",
"basicISDN",
"primaryISDN",
"propPointToPointSerial",
"ppp",
"softwareLoopback",
"eon",
"ethernet-3Mbit",
"nsip",
"slip",
"ultra",
"ds3",
"sip",
"frame-relay",
"RS-232",
"Parallel",
"arcnet",
"arcnet-plus",
"atm",
"MIOX25",
"SONET",
"x25ple",
"iso88022llc",
"localTalk",
"smds-dxi",
"frameRelayService",
"v35",
"hssi",
"hippi",
"modem",
"aal5",
"sonetPath",
"sonetVT",
"smds-icip",
"propVirtual",
"propMultiLink",
"ieee80212",
"fibre-channel",
"hippiInterfaces",
"FrameRelayInterconnect",
"aflane8023",
"aflane8025",
"cctEmul",
"fastEther",
"isdn",
"v11",
"v36",
"g703-64k",
"g703-2mb",
"qllc",
"fastEtherFX",
"channel",
"IEEE802.11",
"ibm370parChan",
"ESCON",
"DLSw",
"ISDNs",
"ISDNu",
"lapd",
"ip-switch",
"rsrb",
"atm-logical",
"ds0",
"ds0Bundle",
"bsc",
"async",
"cnr",
"iso88025Dtr",
"eplrs",
"arap",
"propCnls",
"hostPad",
"termPad",
"frameRelayMPI",
"x213",
"adsl",
"radsl",
"sdsl",
"vdsl",
"iso88025CRFPInt",
"myrinet",
"voiceEM",
"voiceFXO",
"voiceFXS",
"voiceEncap",
"voiceOverIp",
"atmDxi",
"atmFuni",
"atmIma",
"pppMultilinkBundle",
"ipOverCdlc",
"ipOverClaw",
"stackToStack",
"virtualIpAddress",
"mpc",
"ipOverAtm",
"iso88025Fiber",
"tdlc",
"gigabitEthernet",
"hdlc",
"lapf",
"v37",
"x25mlp",
"x25huntGroup",
"transpHdlc",
"interleave",
"fast",
"ip",
"docsCableMaclayer",
"docsCableDownstream",
"docsCableUpstream",
"a12MppSwitch",
"tunnel",
"coffee",
"ces",
"atmSubInterface",
"l2vlan",
"l3ipvlan",
"l3ipxvlan",
"digitalPowerLine",
"mediaMailOverIp",
"dtm",
"dcn",
"ipForward",
"msdsl",
"ieee1394     IEEE1394",
"if-gsn",
"dvbRccMacLayer",
"dvbRccDownstream",
"dvbRccUpstream",
"atmVirtual",
"mplsTunnel",
"srp",
"voiceOverAtm",
"voiceOverFrameRelay",
"idsl",
"compositeLink",
"ss7SigLink",
"propWirelessP2P",
"frForward",
"rfc1483",
"USB",
"ieee8023adLag",
"bgpPolicyAccounting",
"frf16MfrBundle",
"h323Gatekeeper",
"h323Proxy",
"mpls",
"mfSigLink",
"hdsl2",
"shdsl",
"ds1FDL",
"POS",
"dvbAsiIn",
"dvbAsiOut",
"plc",
"NFAS",
"TR008",
"GR303RDT",
"GR303IDT",
"ISUP",
"propDocsWirelessMaclayer",
"propDocsWirelessDownstream",
"propDocsWirelessUpstream",
"hiperlan2",
"propBWAp2Mp",
"sonetOverheadChannel",
"digitalWrapperOverheadChannel",
"aal2",
"radioMAC",
"atmRadio",
"IMT",
"mvl",
"reachDSL",
"frDlciEndPt",
"atmVciEndPt",
"opticalChannel",
"opticalTransport",
"propAtm",
"voiceOverCable",
"infiniband",
"teLink",
"q2931",
"virtualTg",
"sipTg",
"sipSig",
"docsCableUpstreamChannel",
"econet",
"pon155",
"pon622",
"bridge",
"linegroup",
"voiceEMFGD",
"voiceFGDEANA",
"voiceDID",
"mpegTransport",
"sixToFour",
"gtp",
"pdnEtherLoop1",
"pdnEtherLoop2",
"opticalChannelGroup",
"homepna",
"gfp",
"ciscoISLvlan",
"actelisMetaLOOP",
"fcipLink",
"rpr",
"qam",
"lmp",
"cblVectaStar",
"docsCableMCmtsDownstream",
"adsl2",
"macSecControlledIF",
"macSecUncontrolledIF",
"aviciOpticalEther",
"atmbond",
"voiceFGDOS",
"mocaVersion1",
"ieee80216WMAN",
"adsl2plus",
"dvbRcsMacLayer",
"dvbTdm",
"dvbRcsTdma",
"x86Laps",
"wwanPP",
"wwanPP2",
"voiceEBS",
"ifPwType",
"ILAN",
"PIP",
"aluELP",
"gpon",
"vdsl2",
"capwapDot11Profile",
"capwapDot11Bss",
"capwapWtpVirtualRadio",
"bits",
"docsCableUpstreamRfPort",
"cableDownstreamRfPort",
"vmwareVirtualNic",
"ieee802154",
"otnOdu",
"otnOtu",
"ifVfiType",
"g9981",
"g9982",
"g9983",
"aluEpon (E-PON)",
"aluEponOnu",
"aluEponPhysicalUni",
"aluEponLogicalLink",
"aluGponOnu",
"aluGponPhysicalUni",
"vmwareNicTeam",
"Reserved",
"Reserved",
"Reserved",
"Reserved",
"docsOfdmDownstream",
"docsOfdmaUpstream",
"gfast",
"sdci",
"xboxWireless",
"fastdsl",
"docsCableScte55d1FwdOob",
"docsCableScte55d1RetOob",
"docsCableScte55d2DsOob",
"docsCableScte55d2UsOob",
"docsCableNdf",
"docsCableNdr",
"ptm",
"ghn",
};

static const char *const if_typesd[] = {
"Description",
"none of the following",
"BBN Report 1822",
"BBN Report 1822",
"BBN Report 1822",
"X.25",
"",
"DEPRECATED",
"Token Bus-like Objects",
"Token Ring-like Objects",
"",
"DEPRECATED",
"",
"",
"",
"FDDI Objects",
"LAP B",
"",
"T1/E1 Carrier Objects",
"obsolete",
"",
"",
"",
"Point-to-Point Protocol",
"",
"",
"",
"",
"",
"",
"DS3/E3 Interface Objects",
"SMDS Interface Objects",
"Frame Relay Objects for DTE",
"RS-232 Objects",
"Parallel Printer Objects",
"ARC network",
"ARC network plus",
"ATM",
"MIOX25",
"SONET or SDH",
"X.25 packet level",
"802.2 LLC",
"",
"SMDS DXI",
"Frame Relay DCE",
"V.35",
"HSSI",
"HIPPI",
"generic modem",
"AAL5 over ATM",
"",
"",
"SMDS Inter-Carrier Interface Protocol",
"proprietary vitural/internal interface",
"proprietary multi-link multiplexing",
"100BaseVG",
"Fibre Channel",
"HIPPI interfaces",
"Interconnet over FR",
"ATM Emulated LAN for 802.3",
"ATM Emulated LAN for 802.5",
"ATM Emulated circuit",
"DEPRECATED",
"ISDN and X.25",
"CCITT V.11/X.21",
"CCITT V.36",
"CCITT G703 at 64Kbps",
"CCITT G703 at 2Mbps",
"SNA QLLC",
"DEPRECATED",
"channel",
"radio spread spectrum",
"IBM System 360/370 OEMI Channel",
"IBM Enterprise Systems Connection",
"Data Link Switching",
"ISDN S/T interface",
"ISDN U interface",
"Link Access Protocol D",
"IP Switching Objects",
"Remote Source Route Bridging",
"ATM Logical Port",
"Digital Signal Level 0",
"group of ds0s on the same ds1",
"Bisynchronous Protocol",
"Asynchronous Protocol",
"Combat Net Radio",
"ISO 802.5r DTR",
"Enhanced  Pos Loc Report Sys",
"Appletalk Remote Access Protocol",
"Proprietary Connectionless Proto.",
"CCITT-ITU X.29 PAD Protocol",
"CCITT-ITU X.3 PAD Facility",
"Multiproto Interconnect over FR",
"CCITT-ITU X213",
"Asymmetric Digital Subscriber Loop",
"Rate-Adapt. Digital Subscriber Loop",
"Symmetric Digital Subscriber Loop",
"Very H-Speed Digital Subscrib. Loop",
"ISO 802.5 CRFP",
"Myricom Myrinet",
"Voice recEive and transMit (E&M)",
"Voice Foreign Exchange Office",
"Voice Foreign Exchange Station",
"Voice encapsulation",
"Voice over IP encapsulation",
"ATM DXI",
"ATM FUNI",
"ATM IMA",
"PPP Multilink Bundle",
"IBM ipOverCdlc",
"IBM Common Link Access to Workstn",
"IBM stackToStack",
"IBM VIPA",
"IBM multi-protocol channel support",
"IBM ipOverAtm",
"ISO 802.5j Fiber Token Ring",
"IBM twinaxial data link control",
"DEPRECATED",
"HDLC",
"LAP F",
"V.37",
"Multi-Link Protocol",
"X25 Hunt Group",
"Transp HDLC",
"Interleave channel",
"Fast channel",
"IP (for APPN HPR in IP networks)",
"CATV Mac Layer",
"CATV Downstream interface",
"CATV Upstream interface",
"Avalon Parallel Processor",
"Encapsulation interface",
"coffee pot",
"Circiut Emulation Service",
"(x)  ATM Sub Interface",
"Layer 2 Virtual LAN using 802.1Q",
"Layer 3 Virtual LAN - IP Protocol",
"Layer 3 Virtual LAN - IPX Prot.",
"IP over Power Lines",
"(xxx)  Multimedia Mail over IP",
"Dynamic synchronous Transfer Mode",
"Data Communications Network",
"IP Forwarding Interface",
"Multi-rate Symmetric DSL",
"High Performance Serial Bus",
"HIPPI-6400",
"DVB-RCC MAC Layer",
"DVB-RCC Downstream Channel",
"DVB-RCC Upstream Channel",
"ATM Virtual Interface",
"MPLS Tunnel Virtual Interface",
"Spatial Reuse Protocol",
"Voice over ATM",
"Voice Over Frame Relay",
"Digital Subscriber Loop over ISDN",
"Avici Composite Link Interface",
"SS7 Signaling Link",
"Prop. P2P wireless interface",
"Frame forward Interface",
"Multiprotocol over ATM AAL5",
"USB Interface",
"IEEE 802.3ad Link Aggregate",
"BGP Policy Accounting",
"FRF.16 Multilik Frame Relay",
"H323 Gatekeeper",
"H323 Voice and Video Proxy",
"MPLS",
"Multi-frequency signaling link",
"High Bit-Rate DSL, 2nd gen.",
"Multirate HDSL2",
"Facility Data Link (4Kbps) on a DS1",
"Packet over SONET/SDH Interface",
"DVB-ASI Input",
"DVB-ASI Output",
"Power Line Communications",
"Non-Facility Associated Signaling",
"TROO8",
"Remote Digital Terminal",
"Integrated Digital Terminal",
"ISUP",
"Cisco proprietary Maclayer",
"Cisco proprietary Downstream",
"Cisco proprietary Upstream",
"HIPERLAN Type 2 Radio Interface",
"PropBroadbandWirelessAccesspt2Multipt (use of this type for IEEE 802.16 WMAN, interfaces as per IEEE 802.16 is deprecated and iftype 237 should be used instead)",
"SONET Overhead Channel",
"Digital Wrapper Overhead",
"ATM adaptation layer 2",
"MAC layer over radio links",
"ATM over radio links",
"Inter-Machine Trunks",
"Multiple Virtual Lines DSL",
"Long Reach DSL",
"Frame Relay DLCI End Point",
"ATM VCI End Point",
"Optical Channel",
"Optical Transport",
"Proprietary ATM",
"Voice Over Cable Interface",
"Infiniband",
"TE Link",
"Q.2931",
"Virtual Trunk Group",
"SIP Trunk Group",
"SIP Signaling",
"CATV Upstream Channel",
"Acorn Econet",
"FSAN 155Mb Symetrical PON interface",
"FSAN 622Mb Symetrical PON interface",
"Transparent bridge interface",
"Interface common to multiple lines",
"voice E&M Feature Group D",
"voice FGD Exchange Access North American",
"voice Direct Inward Dialing",
"MPEG transport interface",
"6to4 interface  (DEPRECATED)",
"GTP (GPRS Tunneling Protocol)",
"Paradyne EtherLoop 1",
"Paradyne EtherLoop 2",
"Optical Channel Group",
"HomePNA ITU-T G.989",
"Generic Framing Procedure (GFP)",
"Layer 2 Virtual LAN using Cisco ISL",
"Acteleis proprietary MetaLOOP High Speed Link",
"FCIP Link",
"Resilient Packet Ring Interface Type",
"RF Qam Interface",
"Link Management Protocol",
"Cambridge Broadband Networks Limited VectaStar",
"CATV Modular CMTS Downstream Interface",
"Asymmetric Digital Subscriber Loop Version 2 (DEPRECATED - REPLACED BY 238)",
"MACSecControlled",
"MACSecUncontrolled",
"Avici Optical Ethernet Aggregate",
"atmbond",
"voice FGD Operator Services",
"MultiMedia over Coax Alliance",
"IEEE 802.16 WMAN interface",
"Asymmetric Digital Subscriber Loop Version 2 -- Version 2 Plus and all variants",
"DVB-RCS MAC Layer",
"DVB Satellite TDM",
"DVB-RCS TDMA",
"LAPS based on ITU-T X.86/Y.1323",
"3GPP WWAN",
"3GPP2 WWAN",
"voice P-phone EBS physical interface",
"Pseudowire interface type",
"Internal LAN on a bridge per IEEE 802.1ap",
"Provider Instance Port on a bridge per IEEE 802.1ah PBB",
"Alcatel-Lucent Ethernet Link Protection",
"Gigabit-capable passive optical networks (G-PON)  as per ITU-T G.948",
"Very high speed digital subscriber line Version 2 (as per ITU-T Recommendation G.993.2)",
"WLAN Profile Interface",
"WLAN BSS Interface",
"WTP Virtual Radio Interface",
"bitsport",
"DOCSIS CATV Upstream RF Port",
"CATV downstream RF port",
"VMware Virtual Network Interface",
"IEEE 802.15.4 WPAN interface",
"OTN Optical Data Unit",
"OTN Optical channel Transport Unit",
"VPLS Forwarding Instance Interface Type",
"G.998.1 bonded interface",
"G.998.2 bonded interface",
"G.998.3 bonded interface",
"Ethernet Passive Optical Networks",
"EPON Optical Network Unit",
"EPON physical User to Network interface",
"The emulation of a point-to-point link over the EPON layer",
"GPON Optical Network Unit",
"GPON physical User to Network interface",
"VMware NIC Team",
"The corresponding transmission value is allocated according to the following reference.",
"The corresponding transmission value is allocated according to the following reference.",
"The corresponding transmission value is allocated according to the following reference.",
"The corresponding transmission value is allocated according to the following reference.",
"CATV Downstream OFDM interface",
"CATV Upstream OFDMA interface",
"G.fast port",
"SDCI (IO-Link)",
"Xbox wireless",
"FastDSL",
"Cable SCTE 55-1 OOB Forward Channel",
"Cable SCTE 55-1 OOB Return Channel",
"Cable SCTE 55-2 OOB Downstream Channel",
"Cable SCTE 55-2 OOB Upstream Channel",
"Cable Narrowband Digital Forward",
"Cable Narrowband Digital Return",
"Packet Transfer Mode",
"G.hn port",
};

#define NIFTYPES ((sizeof if_types)/(sizeof if_types[0]))
#define NIFTYPESD ((sizeof if_typesd)/(sizeof if_typesd[0]))
